//! C# language plugin for Codebuddy
//!
//! Provides AST parsing, symbol extraction, and manifest analysis for C#.

// Modules for plugin functionality
mod manifest;
mod parser;

// Core plugin traits and types
use async_trait::async_trait;
use cb_plugin_api::{
    LanguageCapabilities, LanguageMetadata, LanguagePlugin, ManifestData, ParsedSource,
    PluginResult,
};
use std::path::Path;

/// C# language plugin implementation
pub struct CSharpPlugin {
    metadata: LanguageMetadata,
}

impl CSharpPlugin {
    /// Create a new C# plugin instance
    pub fn new() -> Self {
        Self {
            // NOTE: This will be auto-generated by build.rs from languages.toml
            metadata: LanguageMetadata::CSHARP,
        }
    }
}

// Default implementation for plugin registration
impl Default for CSharpPlugin {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl LanguagePlugin for CSharpPlugin {
    fn metadata(&self) -> &LanguageMetadata {
        &self.metadata
    }

    fn capabilities(&self) -> LanguageCapabilities {
        LanguageCapabilities {
            imports: false,  // TODO: Can be enabled later
            workspace: false, // TODO: Can be enabled later
        }
    }

    async fn parse(&self, source: &str) -> PluginResult<ParsedSource> {
        parser::parse_source(source)
    }

    async fn analyze_manifest(&self, path: &Path) -> PluginResult<ManifestData> {
        manifest::analyze_manifest(path).await
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_plugin_creation() {
        let plugin = CSharpPlugin::new();
        assert_eq!(plugin.metadata().name, "C#");
    }

    #[test]
    fn test_file_extensions() {
        let plugin = CSharpPlugin::new();
        let extensions = plugin.metadata().extensions;
        assert_eq!(extensions, &["cs"]);
    }

    #[test]
    fn test_capabilities() {
        let plugin = CSharpPlugin::new();
        let caps = plugin.capabilities();
        assert!(!caps.imports);
        assert!(!caps.workspace);
    }
}